apiVersion: v1
kind: Secret
metadata:
  name: env-vars
  namespace: billing
type: Opaque
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | b64enc }}
  PORT: {{ .Values.env.PORT | b64enc }}
  MONGO_URI: {{ .Values.env.MONGO_URI | b64enc }}
  STRIPE_SECRET_KEY: {{ .Values.env.STRIPE_SECRET_KEY | b64enc }}
  STRIPE_SECRET_WEBHOOK: {{ .Values.env.STRIPE_SECRET_WEBHOOK | b64enc }}
